start-leaf-route: direct:leaf

routes-to-execute-leaf: judicial-region-type, judicial-base-location_type

route:
  judicial-region-type:
    id: judicial-region-type
    file-name: Locations-Test
    table-name: region_type
    insert-sql:
      sql:insert into region_type (region_id,region_desc_en,region_desc_cy) values(:#region_id,:#region_desc_en,:#region_desc_cy)
      on conflict (region_id) do update set region_desc_en = :#region_desc_en,region_desc_cy = :#region_desc_cy?dataSource=dataSource&batch=true
    blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data/Locations-Test?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialRegionTypeProcessor
    mapper-class: JudicialRegionTypeRowMapper
    csv-binder-object: JudicialRegionType

  judicial-base-location_type:
    id: judicial-base-location_type
    file-name: BaseLocations-Test
    table-name: base_location_type
    insert-sql:
      sql:insert into base_location_type (base_location_id,court_name,court_type,circuit,area_of_expertise) values(:#base_location_id,:#court_name, :#court_type,:#circuit, :#area_of_expertise)
      on conflict (base_location_id) do update set court_name = :#court_name,court_type = :#court_type,circuit = :#circuit,area_of_expertise = :#area_of_expertise?dataSource=dataSource&batch=true
    blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data/BaseLocations-Test?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialBaseLocationProcessor
    mapper-class: JudicialBaseLocationRowTypeMapper
    csv-binder-object: JudicialBaseLocationType


base-location-select-jrd-sql: SELECT * FROM base_location_type

region-select-jrd-sql: SELECT * FROM region_type

fetch-base-location-id: SELECT base_location_id FROM base_location_type
fetch-region-id: SELECT region_id FROM region_type
fetch-lower-levels: SELECT lower_level FROM judicial_ticket_code_mapping








