spring:
  mail:
    from: no-reply@reform.hmcts.net
    to:  sushant.choudhari@hmcts.net,abhijit.diwan@hmcts.net,mallikarjun.puttana@hmcts.net
    subject:  JRD - Exception in processing -
    host: mta.reform.hmcts.net
    port: 25
    enabled: true
    properties:
      mail-smtp:
        starttls:
          enable: false
        ssl:
          trust: "*"
  flyway:
    locations: classpath:db/testmigration
    enabled: true
  batch:
    initialize-schema: always
    # set batch false in integration test and run batch manually with batch runner to set dynamic test property values
    # eg. dynamic properties ${parent.file.name}
    job:
      enabled: false


start-route: direct:JRD
archival-route: direct:JrdArchival
archival-path: azure-blob://${azure.storage.account-name}/jud-ref-data-archive
archival-file-names: Personal-Test,Appointments-Test,Authorisations-Test,Locations-Test,BaseLocations-Test
archival-cred: credentials=#credsreg&operation=updateBlockBlob
archival-date-format: dd-MM-yyyy
active-blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data
file-read-time-out: 2000
scheduler-audit-select: select count(*) from dataload_schedular_audit where date(scheduler_start_time) = current_date
invalid-exception-sql: insert into dataload_exception_records(table_name,scheduler_start_time,scheduler_name,error_description,updated_timestamp) values(?, ?, ?, ?, ?)
invalid-jsr-sql: insert into dataload_exception_records(table_name,scheduler_start_time,scheduler_name,key,field_in_error,error_description,updated_timestamp) values(?, ?, ?, ?, ?, ?, ?)
scheduler-insert-sql: insert into dataload_schedular_audit (scheduler_name,file_name, scheduler_start_time,scheduler_end_time,status) values(?,?,?,?,?)
jsr-threshold-limit: 5
leaf-route-task: leafRouteTask
parent-route-task: parentRouteOrchestrationTask
batchjob-name: JudicialDataLoad
audit-enable: true

routes-to-execute-orchestration: judicial-user-profile-orchestration, judicial-office-appointment, judicial-office-authorisation
route:
  judicial-user-profile-orchestration:
    id: judicial-user-profile-orchestration
    file-name: Personal-Test
    table-name: judicial_user_profile
    insert-sql:
      sql:insert into judicial_user_profile (per_id,personal_code,appointment,known_as,surname,full_name,post_nominals,appointment_type,work_pattern,ejudiciary_email,joining_date,last_working_date,
      active_flag,extracted_date,created_date,last_loaded_date,object_id)
      values(:#per_id,:#personal_code,:#appointment,:#known_as,:#surname,:#full_name,:#post_nominals,
      :#appointment_type,:#work_pattern, :#ejudiciary_email,TO_DATE(NULLIF(:#joining_date,''), 'yyyy-MM-dd'),TO_DATE(NULLIF(:#last_working_date,''), 'yyyy-MM-dd'),:#active_flag,
      TO_TIMESTAMP(:#extracted_date, 'yyyy-MM-dd HH24:MI:SS.MSUS'), now() at time zone 'utc', now() at time zone 'utc', :#object_id) on conflict (per_id) do update set personal_code = :#personal_code, appointment = :#appointment,
      known_as = :#known_as, surname = :#surname, full_name = :#full_name, post_nominals =:#post_nominals,
      appointment_type = :#appointment_type, work_pattern = :#work_pattern, ejudiciary_email = :#ejudiciary_email, joining_date = TO_DATE(NULLIF(:#joining_date,''), 'yyyy-MM-dd'),
      last_working_date = TO_DATE(NULLIF(:#last_working_date,''), 'yyyy-MM-dd'), active_flag = :#active_flag,
      extracted_date = TO_TIMESTAMP(:#extracted_date, 'yyyy-MM-dd HH24:MI:SS.MSUS'), last_loaded_date = now() at time zone 'utc', object_id = :#object_id?batch=true&dataSource=dataSource
    blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data/Personal-Test?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialUserProfileProcessor
    mapper-class: JudicialUserProfileRowMapper
    csv-binder-object: JudicialUserProfile

  judicial-office-appointment:
    id: judicial-office-appointment
    file-name: Appointments-Test
    table-name: judicial-office-appointment
    truncate-sql:
      sql:truncate judicial_office_appointment restart identity?dataSource=dataSource&batch=true
    insert-sql:
      sql:insert into judicial_office_appointment (judicial_office_appointment_id,per_id,base_location_id,region_id,is_prinicple_appointment,start_date,end_date,active_flag,extracted_date,created_date,last_loaded_date,personal_code)
      values(:#judicial_office_appointment_id, :#per_id, :#base_location_id, :#region_id, :#is_prinicple_appointment,
      TO_DATE(NULLIF(:#start_date,''), 'yyyy-MM-dd'), TO_DATE(NULLIF(:#end_date,''), 'yyyy-MM-dd'), :#active_flag, TO_TIMESTAMP(:#extracted_date, 'yyyy-MM-dd HH24:MI:SS.MSUS'),now() at time zone 'utc',now() at time zone 'utc', :#personal_code)?dataSource=dataSource&batch=true
    blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data/Appointments-Test?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialOfficeAppointmentProcessor
    mapper-class: JudicialOfficeAppointmentRowMapper
    csv-binder-object: JudicialOfficeAppointment

  judicial-office-authorisation:
    id: judicial-office-authorisation
    file-name: Authorisations-Test
    table-name: judicial_office_authorisation
    truncate-sql:
      sql:truncate table judicial_office_authorisation restart identity?dataSource=dataSource
    insert-sql:
      sql:insert into judicial_office_authorisation (judicial_office_auth_id,per_id,jurisdiction,ticket_id,start_date,end_date,created_date,last_updated,lower_level,personal_code)
      values(:#judicial_office_auth_id,:#per_id,:#jurisdiction,:#ticket_id,:#start_date,:#end_date,:#created_date,:#last_updated,:#lower_level,:#personal_code)?dataSource=dataSource&batch=true
    blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data/Authorisations-Test?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialOfficeAuthorisationProcessor
    mapper-class: JudicialOfficeAuthorisationRowMapper
    csv-binder-object: JudicialOfficeAuthorisation

parent-select-jrd-sql: SELECT * FROM judicial_user_profile

child-select-child1-sql: SELECT * FROM judicial_office_appointment

child-select-child2-sql: SELECT * FROM judicial_office_authorisation

exception-select-query: select * from  dataload_exception_records

select-dataload-schedular-audit: select * from dataload_schedular_audit

select-dataload-scheduler-audit-failure: select * from dataload_schedular_audit where status='Failure'

select-dataload-scheduler-audit-partial-success: select *  from dataload_schedular_audit where status='PartialSuccess'

select-dataload-scheduler-audit-success: select *  from dataload_schedular_audit where status='Success'

start-leaf-route: direct:leaf

truncate-audit: truncate dataload_schedular_audit

truncate-exception: truncate dataload_exception_records

jdbc-batch-size: 10

logging-component-name: RD_Judicial_Ref_Data
component:
  name: Judicial Reference Data
mail:
  enabled: true

idempotent-flag-ingestion: true
fetch-personal-per-id: select per_id from judicial_user_profile

launchdarkly:
  sdk:
    key: ${RD_LD_SDK_KEY:}
    environment: ${LAUNCH_DARKLY_ENV:local}
    user: rd
