jdbc-batch-size: 10
routes-to-execute-orchestration: judicial-user-profile-orchestration,judicial-office-appointment,judicial-office-authorisation,judicial-role-type
route:
  judicial-user-profile-orchestration:
    id: judicial-user-profile-orchestration
    file-name: Personal
    table-name: judicial_user_profile
    insert-sql:
      sql:INSERT INTO judicial_user_profile (per_id,personal_code,known_as,surname,full_name,post_nominals,work_pattern,ejudiciary_email,joining_date,last_working_date,
      active_flag,extracted_date,created_date,last_loaded_date,object_id)
      VALUES(:#per_id,:#personal_code,:#known_as,:#surname,:#full_name,:#post_nominals,
      :#work_pattern, :#ejudiciary_email,TO_DATE(NULLIF(:#joining_date,''), 'yyyy-MM-dd'),TO_DATE(NULLIF(:#last_working_date,''), 'yyyy-MM-dd'),:#active_flag,
      TO_TIMESTAMP(:#extracted_date, 'yyyy-MM-dd HH24:MI:SS.MSUS'), NOW() AT TIME ZONE 'utc', NOW() AT TIME ZONE 'utc', :#object_id) on conflict (per_id) do UPDATE SET personal_code = :#personal_code,
      known_as = :#known_as, surname = :#surname, full_name = :#full_name, post_nominals =:#post_nominals,
      work_pattern = :#work_pattern, ejudiciary_email = :#ejudiciary_email, joining_date = TO_DATE(NULLIF(:#joining_date,''), 'yyyy-MM-dd'),
      last_working_date = TO_DATE(NULLIF(:#last_working_date,''), 'yyyy-MM-dd'), active_flag = :#active_flag,
      extracted_date = TO_TIMESTAMP(:#extracted_date, 'yyyy-MM-dd HH24:MI:SS.MSUS'), last_loaded_date = NOW() AT TIME ZONE 'utc' ,object_id = :#object_id?batch=true&dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Personal?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialUserProfileProcessor
    mapper-class: JudicialUserProfileRowMapper
    csv-binder-object: JudicialUserProfile

  judicial-office-appointment:
    id: judicial-office-appointment
    file-name: Appointments
    table-name: judicial_office_appointment
    parent-failure-enabled: true
    parent-name: Personal
    truncate-sql:
      sql:TRUNCATE judicial_office_appointment RESTART IDENTITY?dataSource=dataSource
    insert-sql:
      sql:INSERT INTO judicial_office_appointment (judicial_office_appointment_id,per_id,base_location_id,region_id,is_prinicple_appointment,start_date,end_date,active_flag,extracted_date,created_date,last_loaded_date,personal_code,object_id,
      appointment,appointment_type)
      VALUES(:#judicial_office_appointment_id, :#per_id, :#base_location_id, :#region_id, :#is_prinicple_appointment,
      TO_DATE(NULLIF(:#start_date,''), 'yyyy-MM-dd'), TO_DATE(NULLIF(:#end_date,''), 'yyyy-MM-dd'), :#active_flag, TO_TIMESTAMP(:#extracted_date, 'yyyy-MM-dd HH24:MI:SS.MSUS'),NOW() AT TIME ZONE 'utc',NOW() AT TIME ZONE 'utc', :#personal_code, :#object_id,
      :#appointment, :#appointment_type)?batch=true&dataSource=dataSource
    update-sql:
      sql:UPDATE judicial_office_appointment appt SET epimms_id=jlm.epimms_id,service_code=jlm.service_code FROM (SELECT judicial_base_location_id,base_location_name,epimms_id,service_code FROM judicial_location_mapping) AS jlm WHERE jlm.judicial_base_location_id = appt.base_location_id?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Appointments?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialOfficeAppointmentProcessor
    mapper-class: JudicialOfficeAppointmentRowMapper
    csv-binder-object: JudicialOfficeAppointment

  judicial-office-authorisation:
    id: judicial-office-authorisation
    file-name: Authorisations
    table-name: judicial_office_authorisation
    parent-failure-enabled: true
    parent-name: Personal
    truncate-sql:
      sql:TRUNCATE TABLE judicial_office_authorisation RESTART IDENTITY?dataSource=dataSource
    insert-sql:
      sql:INSERT INTO judicial_office_authorisation (judicial_office_auth_id,per_id,jurisdiction,ticket_id,start_date,end_date,created_date,last_updated,lower_level,personal_code,object_id,mrd_created_time,mrd_updated_time,mrd_deleted_time)
      VALUES(:#judicial_office_auth_id,:#per_id,:#jurisdiction,:#ticket_id,:#start_date,:#end_date,NOW() AT TIME ZONE 'utc',NOW() AT TIME ZONE 'utc',:#lower_level,:#personal_code, :#object_id ,:#mrd_created_time ,:#mrd_updated_time ,:#mrd_deleted_time )?batch=true&dataSource=dataSource
    update-sql:
      sql:UPDATE judicial_office_authorisation auth SET ticket_code=jtm.ticket_code FROM (SELECT ticket_code,jurisdiction,lower_level FROM judicial_ticket_code_mapping) AS jtm WHERE jtm.jurisdiction = auth.jurisdiction and jtm.lower_level = auth.lower_level?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Authorisations?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialOfficeAuthorisationProcessor
    mapper-class: JudicialOfficeAuthorisationRowMapper
    csv-binder-object: JudicialOfficeAuthorisation
  judicial-role-type:
    id: judicial-role-type
    file-name: AdditionalInfoRoles
    table-name: judicial_role_type
    parent-failure-enabled: true
    #Personal-Test only for testing else -Test not needed by main code
    parent-name: Personal
    truncate-sql:
      sql:TRUNCATE TABLE judicial_role_type RESTART IDENTITY?dataSource=dataSource
    insert-sql:
      sql:INSERT INTO judicial_role_type (per_Id,title,location,start_date,end_date)
      VALUES(:#per_Id,:#title,:#location,:#start_date,:#end_date)?batch=true&dataSource=dataSource
    blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data/AdditionalInfoRoles?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialUserRoleTypeProcessor
    mapper-class: JudicialRoleTypeRowMapper
    csv-binder-object: JudicialUserRoleType



