server:
  port: ${PORT:8094}

management:
  endpoints:
    web:
      base-path: "/"

  endpoint:
    health:
      show-details: "always"

spring:
  application:
    name: Judicial reference data blob store sync API

  batch:
    initialize-schema: always
    #run spring batch job manually as need to validate idempotent condition in code
    #rather than giving control to spring
    job:
      enabled: false
  jackson.date-format: yyyy-MM-dd
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration,classpath:db/postgres
    schemas: dbjuddata

  ### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5456}/${POSTGRES_NAME:dbjuddata}${POSTGRES_CONNECTION_OPTIONS:}
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}
    properties:
      charSet: UTF-8
    hikari:
      max-lifetime: 600000
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 1

  profiles:
    include:
      - jrd-router-orchestartion
      - jrd-leaf-router
      - lib


aggregation-strategy-completion-size: 100
aggregation-strategy-timeout: 2000
start-route: direct:JRD
archival-route: direct:JrdArchival
archival-path: azure-blob://${azure.storage.account-name}/jud-ref-data-archive
active-blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data
archival-file-names: Personal,Appointments,Roles,Contracts,Locations,BaseLocations
archival-cred: credentials=#credsreg&operation=updateBlockBlob
archival-date-format: dd-MM-yyyy--HH-mm
file-read-time-out: 180000
leaf-route-task: leafRouteTask
parent-route-task: parentRouteOrchestrationTask
batchjob-name: JudicialDataLoad
scheduler-audit-select: select count(*) from dataload_schedular_audit where date(scheduler_start_time) = current_date
invalid-exception-sql: insert into dataload_exception_records(file_name,scheduler_start_time,scheduler_name,error_description,updated_timestamp) values(?, ?, ?, ?, ?)
invalid-jsr-sql: insert into dataload_exception_records(table_name,scheduler_start_time,scheduler_name,key,field_in_error,error_description,updated_timestamp) values(?, ?, ?, ?, ?, ?, ?)
#jsr-threshold-limit: 100
scheduler-insert-sql:  insert into dataload_schedular_audit (scheduler_name,scheduler_start_time,scheduler_end_time,scheduler_status) values(?, ?, ?, ?)
start-leaf-route: direct:leaf
audit-enable: true



logging-component-name: RD_Judicial_Ref_Data
