aggregation-strategy-completion-size: 100
aggregation-strategy-timeout: 2000
start-route: direct:JRD
archival-route: direct:JrdArchival
archival-path: azure-blob://${azure.storage.account-name}/jud-ref-data-archive
active-blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data
archival-file-names: Personal,Appointments,Authorisations,Roles,Locations,BaseLocations

archival-cred: credentials=#credsreg&operation=updateBlockBlob
archival-date-format: dd-MM-yyyy--HH-mm
file-read-time-out: 180000
leaf-route-task: leafRouteTask
parent-route-task: parentRouteOrchestrationTask
batchjob-name: JudicialDataLoad
scheduler-audit-select: select count(*) from dataload_schedular_audit where date(scheduler_start_time) = current_date
invalid-exception-sql: insert into dataload_exception_records(table_name,scheduler_start_time,scheduler_name,error_description,updated_timestamp) values(?, ?, ?, ?, ?)
invalid-jsr-sql: insert into dataload_exception_records(table_name,scheduler_start_time,scheduler_name,key,field_in_error,error_description,updated_timestamp,row_id) values(?, ?, ?, ?, ?, ?, ?, ?)
#jsr-threshold-limit: 100
scheduler-insert-sql: insert into dataload_schedular_audit (scheduler_name,file_name, scheduler_start_time,scheduler_end_time,status) values(?,?,?,?,?)
start-leaf-route: direct:leaf
audit-enable: true
update-sidam-ids: update judicial_user_profile set sidam_id = ? where object_id = ? and sidam_id is null

logging-component-name: RD_Judicial_Ref_Data
component:
  name: Judicial Reference Data

fetch-personal-per-id: select per_id from judicial_user_profile
fetch-base-location-id: SELECT base_location_id FROM base_location_type
fetch-region-id: SELECT region_id FROM region_type
fetch-contract-id: SELECT contract_type_id FROM contract_type
fetch-role-id: SELECT role_id FROM judicial_role_type

insert-job-sql: insert into dataload_schedular_job(job_start_time, publishing_status) values(?, ?)
update-job-sql: update dataload_schedular_job set job_end_time = now() at time zone 'utc', publishing_status = ? where id =?
select-job-status-sql:  select id, publishing_status from dataload_schedular_job where date(job_start_time) = current_date
get-sidam-ids: select sidam_id from judicial_user_profile where sidam_id is not null
scheduler-audit-failure: select count(*) from dataload_schedular_audit where date(scheduler_start_time) = current_date and status = 'Failure'

jrd:
  publisher:
    azure:
      service:
        bus:
          connection-string: ${JUDICIAL_TOPIC_PRIMARY_CONNECTION_STRING:}
          topic: ${JRD_MQ_TOPIC_NAME:rd-judicial-topic-aat}
          # DO NOT SET THIS 'true' IN PRODUCTION!
          trustAllCerts: ${JRD_MQ_TRUST_ALL_CERTS:false}
    jrd-message-batch-size: ${JRD_DATA_PER_MESSAGE:50}