aggregation-strategy-completion-size: 100
aggregation-strategy-timeout: 2000
start-route: direct:JRD
archival-route: direct:JrdArchival
archival-path: azure-blob://${azure.storage.account-name}/jud-ref-data-archive
active-blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data
archival-file-names: Personal,Appointments,Authorisations,AdditionalInfoRoles,Locations,BaseLocations

archival-cred: credentials=#credsreg&operation=updateBlockBlob
archival-date-format: dd-MM-yyyy--HH-mm
file-read-time-out: 180000
leaf-route-task: leafRouteTask
parent-route-task: parentRouteOrchestrationTask
batchjob-name: JudicialDataLoad
scheduler-audit-select: SELECT COUNT(*) FROM dataload_schedular_audit WHERE date(scheduler_start_time) = current_date
scheduler-audit-prev-day: SELECT file_name, scheduler_start_time, status FROM dataload_schedular_audit WHERE date(scheduler_start_time) = current_date - INTEGER '1'
invalid-exception-sql: INSERT INTO dataload_exception_records(table_name,scheduler_start_time,scheduler_name,error_description,updated_timestamp) VALUES(?, ?, ?, ?, ?)
invalid-jsr-sql: INSERT INTO dataload_exception_records(table_name,scheduler_start_time,scheduler_name,key,field_in_error,error_description,updated_timestamp,row_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?)
#jsr-threshold-limit: 100
scheduler-insert-sql: INSERT INTO dataload_schedular_audit (scheduler_name,file_name, scheduler_start_time,scheduler_end_time,status) VALUES(?,?,?,?,?)
start-leaf-route: direct:leaf
audit-enable: true
update-sidam-ids: UPDATE judicial_user_profile SET sidam_id = ? WHERE object_id = ? AND sidam_id IS NULL

logging-component-name: RD_Judicial_Ref_Data
component:
  name: Judicial Reference Data

fetch-personal-per-id: SELECT per_id FROM judicial_user_profile
fetch-base-location-id: SELECT base_location_id FROM base_location_type
fetch-region-id: SELECT region_id FROM region_type
fetch-contract-id: SELECT contract_type_id FROM contract_type
fetch-role-id: SELECT role_id FROM judicial_role_type
fetch-lower-levels: SELECT lower_level FROM judicial_ticket_code_mapping

insert-job-sql: INSERT INTO dataload_schedular_job(job_start_time, publishing_status) VALUES(?, ?)
update-job-sql: UPDATE dataload_schedular_job SET job_end_time = NOW() AT TIME ZONE 'utc', publishing_status = ? WHERE id =?
select-job-status-sql:  SELECT id, publishing_status FROM dataload_schedular_job WHERE DATE(job_start_time) = current_date
previous-day-job-status: SELECT id, publishing_status FROM dataload_schedular_job WHERE DATE(job_start_time) = current_date - INTEGER '1'
get-sidam-ids: SELECT DISTINCT sidam_id FROM judicial_user_profile WHERE sidam_id IS NOT NULL
scheduler-audit-failure: SELECT COUNT(*) FROM dataload_schedular_audit WHERE DATE(scheduler_start_time) = current_date AND status = 'Failure'
scheduler-end-time: SELECT max(scheduler_end_time) FROM dataload_schedular_audit WHERE scheduler_end_time < ( SELECT MAX(scheduler_end_time) FROM dataload_schedular_audit WHERE file_name = 'Personal' AND status IN ('PartialSuccess', 'Success')) AND file_name = 'Personal' AND status IN ('PartialSuccess', 'Success')

elink-select-job-status-sql:  SELECT id, publishing_status FROM dbjudicialdata.dataload_schedular_job WHERE DATE(job_start_time) = current_date
elink-get-sidam-ids: SELECT DISTINCT sidam_id FROM dbjudicialdata.judicial_user_profile WHERE sidam_id IS NOT NULL
elink-update-job-sql: UPDATE dbjudicialdata.dataload_schedular_job SET job_end_time = NOW() AT TIME ZONE 'utc', publishing_status = ? WHERE id =?
elink-insert-job-sql: INSERT INTO dbjudicialdata.dataload_schedular_job(job_start_time, publishing_status) VALUES(?, ?)
jrd:
  publisher:
    azure:
      service:
        bus:
          connection-string: ${JUDICIAL_TOPIC_PRIMARY_CONNECTION_STRING:}
          topic: ${JRD_MQ_TOPIC_NAME:rd-judicial-topic-aat}
          # DO NOT SET THIS 'true' IN PRODUCTION!
          trustAllCerts: ${JRD_MQ_TRUST_ALL_CERTS:false}
    jrd-message-batch-size: ${JRD_DATA_PER_MESSAGE:50}

elink:
  publisher:
    azure:
      service:
        bus:
          connection-string: ${JUDICIAL_TOPIC_PRIMARY_CONNECTION_STRING:}
          topic: ${JRD_MQ_TOPIC_NAME:rd-judicial-topic-aat}
          # DO NOT SET THIS 'true' IN PRODUCTION!
          trustAllCerts: ${JRD_MQ_TRUST_ALL_CERTS:true}
    jrd-message-batch-size: ${JRD_DATA_PER_MESSAGE:50}