start-leaf-route: direct:leaf
leaf-route-names: judicial-role-type,judicial-contract-type,judicial-region-type,judicial-base-location_type

leaf-route:
  judicial-role-type:
    id: judicial-role-type
    insert-sql:
      sql:insert into judicial_role_type (role_id,role_desc_en,role_desc_cy) values(:#role_id,:#role_desc_en,:#role_desc_cy)
      on conflict (role_id) do update set role_desc_en = :#role_desc_en,role_desc_cy = :#role_desc_cy?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Roles.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialUserRoleTypeProcessor
    mapper-class: JudicialRoleTypeRowMapper
    csv-binder-object: JudicialUserRoleType

  judicial-contract-type:
    id: judicial-contract-type
    insert-sql:
      sql:insert into contract_type (contract_type_id,contract_type_desc_en,contract_type_desc_cy) values(:#contract_type_id,:#contract_type_desc_en,:#contract_type_desc_en)
      on conflict (contract_type_id) do update set contract_type_desc_en = :#contract_type_desc_en,contract_type_desc_cy = :#contract_type_desc_cy?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Contracts.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialContractTypeProcessor
    mapper-class: JudicialContractTypeRowMapper
    csv-binder-object: JudicialContractType

  judicial-region-type:
    id: judicial-region-type
    insert-sql:
      sql:insert into region_type (region_id,region_desc_en,region_desc_cy) values(:#region_id,:#region_desc_en,:#region_desc_cy)
      on conflict (region_id) do update set region_desc_en = :#region_desc_en,region_desc_cy = :#region_desc_cy?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Locations.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialRegionTypeProcessor
    mapper-class: JudicialRegionTypeRowMapper
    csv-binder-object: JudicialRegionType

  judicial-base-location_type:
    id: judicial-base-location_type
    insert-sql:
      sql:insert into base_location_type (base_location_id,court_name,court_type,circuit,area_of_expertise) values(:#base_location_id,:#court_name, :#court_type,:#circuit, :#area_of_expertise)
      on conflict (base_location_id) do update set court_name = :#court_name,court_type = :#court_type,circuit = :#circuit,area_of_expertise = :#area_of_expertise?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/BaseLocations.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialBaseLocationProcessor
    mapper-class: JudicialBaseLocationRowTypeMapper
    csv-binder-object: JudicialBaseLocationType


