start-leaf-route: direct:leaf
leaf-route-names: judicial-role-type,judicial-contract-type

leaf-route:
  judicial-role-type:
    id: judicial-role-type
    insert-sql:
      sql:insert into judicial_role_type (role_id,role_desc_en,role_desc_cy) values(:#role_id,:#role_desc_en,:#role_desc_cy)?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Roles.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialUserRoleTypeProcessor
    mapper-class: JudicialRoleTypeRowMapper
    csv-binder-object: JudicialUserRoleType

  judicial-contract-type:
    id: judicial-contract-type
    insert-sql:
      sql:insert into contract_type (contract_type_id,contract_type_desc_en,contract_type_desc_cy) values(:#contract_type_id,:#contract_type_desc_en,:#contract_type_desc_en)?dataSource=dataSource
    blob-path:
      azure-blob://${azure.storage.account-name}/jud-ref-data/Contracts.csv?credentials=#credsreg&operation=updateBlockBlob
    processor-class: JudicialContractTypeProcessor
    mapper-class: JudicialContractTypeRowMapper
    csv-binder-object: JudicialContractType



