server:
  port: ${PORT:8094}

management:
  endpoints:
    web:
      base-path: "/"

  endpoint:
    health:
      show-details: "always"

spring:
  application:
    name: Judicial reference data blob store sync API

  batch:
    initialize-schema: always
    #run spring batch job manually as need to validate idempotent condition in code
    #rather than giving control to spring
    job:
      enabled: false
  jackson.date-format: yyyy-MM-dd
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration,classpath:db/postgres
    schemas: dbjuddata

  ### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5456}/${POSTGRES_NAME:dbjuddata}${POSTGRES_CONNECTION_OPTIONS:}
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}
    properties:
      charSet: UTF-8
    hikari:
      max-lifetime: 600000
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 1

  profiles:
    include:
      - jrd-router-orchestartion
      - jrd-leaf-router
      - lib
      - camel-routes-common
mail:
  enabled: false

ACCOUNT_NAME: rdpreview
ACCOUNT_KEY: 61Sb95N8fFF5PNn/Gn5FjJFUg6wKJ/j6IWa0URdnAWnmjtluRPpJDk8uA3Zrx+u9gzUA8nF56rVJm1jl5dgTnQ==
CONTAINER_NAME: jud-ref-data


