server:
  port: ${PORT:8094}

management:
  endpoints:
    jmx:
      exposure:
        include: 'health'
    web:
      base-path: "/"
  endpoint:
    health:
      show-details: "always"

spring:
  application:
    name: Judicial reference data blob store sync API
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson.date-format: yyyy-MM-dd
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration,classpath:db/postgres

  mail:
    from: no-reply@reform.hmcts.net
    to:  Praveen.Saxena@HMCTS.NET
    subject:  Exception received at Rout
    host: mta.reform.hmcts.net
    port: 25
    enabled: false
    properties:
      mail-smtp:
        starttls:
          enable: false
        ssl:
          trust: "*"

  ### database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5456}/${POSTGRES_NAME:dbjuddata}${POSTGRES_CONNECTION_OPTIONS:}
    username: ${POSTGRES_USERNAME:dbjuddata}
    password: ${POSTGRES_PASSWORD:dbjuddata}
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

  profiles:
    include:
      - jrd-router
      - jrd-leaf-router


# Scheduler configuration
scheduler:
  camel-route-config: 0 0 22 * * ?
  camel-leaf-router-config: 0 0 21 * * ?

azure:
  storage:
    account-name: ${ACCOUNT_NAME:ACCOUNT_NAME}
    account-key: ${ACCOUNT_KEY:ACCOUNT_KEY}
    container-name: ${CONTAINER_NAME:CONTAINER_NAME}
    blob-url-suffix: ${BLOB_URL_SUFFIX:BLOB_URL_SUFFIX}

