apiVersion: v2
appVersion: "0.1"
description:  Data load from Judicial HR systems
name: rd-judicial-data-load
home: https://github.com/hmcts/rd-judicial-data-load
version: 0.3.8

maintainers:
  - name: Reference Data Team
dependencies:
  - name: job
    version: ~0.7.3
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: postgresql
    version: 11.6.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: servicebus
    version: v0.4.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: servicebus.enabled
  - name: blobstorage
    version: 0.3.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: blobstorage.enabled