apiVersion: v2
appVersion: "0.1"
description:  Data load from Judicial HR systems
name: rd-judicial-data-load
home: https://github.com/hmcts/rd-judicial-data-load
version: 0.1.8
maintainers:
  - name: Reference Data Team