job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: dbjuddata
    POSTGRES_USERNAME: dbjuddata
    POSTGRES_PASSWORD: dbjuddata
    FLYWAY_ENABLED: true
    ENV_NAME: preview
    CONTAINER_NAME: jud-ref-data
    JRD_MQ_TRUST_ALL_CERTS: false
    JRD_DATA_PER_MESSAGE: 500
  keyVaults:
    rd:
      secrets:
        - CONTAINER-NAME
        - BLOB-URL-SUFFIX
        - ApplicationInsightsInstrumentationKey
        - judicial-topic-primary-connection-string
        - LD-SDK-KEY
  secrets:
    SB_TOPIC_CONN_STRING:
      secretRef: servicebus-secret-topic-{{ .Release.Name }}-servicebus-jrd-aks-topic
      key: connectionString
global:
  jobKind: CronJob

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: dbjuddata
  postgresqlPassword: dbjuddata
  postgresqlDatabase: dbjuddata
  persistence:
    enabled: false

servicebus:
  resourceGroup: rd
  teamName: "RD"
  location: uksouth
  serviceplan: standard
  setup:
    topics:
      - name: jrd-aks-topic
        subscriptionNeeded: yes
  enabled: true
