job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: dbjuddata
    POSTGRES_USERNAME: dbjuddata
    POSTGRES_PASSWORD: dbjuddata
    FLYWAY_ENABLED: true
    ACCOUNT_NAME: $(BLOB_ACCOUNT_NAME)
    ACCOUNT_KEY: $(BLOB_ACCESS_KEY)
    ENV_NAME: preview
    CONTAINER_NAME: jud-ref-data
  keyVaults:
    rd:
      secrets:
        - CONTAINER-NAME
        - BLOB-URL-SUFFIX
        - ApplicationInsightsInstrumentationKey
  secrets:
    BLOB_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    BLOB_ACCESS_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    BLOB_SERVICE_ENDPOINT:
      secretRef: storage-secret-{{ .Release.Name }}
      key: primaryBlobServiceEndPoint
global:
  jobKind: CronJob

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: dbjuddata
  postgresqlPassword: dbjuddata
  postgresqlDatabase: dbjuddata
  persistence:
    enabled: false

blobstorage:
  resourceGroup: rd
  teamName: "RD"
  location: uksouth
  setup:
    containers:
    - jud-ref-data
    - jud-ref-data-archive
  enabled: true
