job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: dbjuddata
    POSTGRES_USERNAME: dbjuddata
    POSTGRES_PASSWORD: dbjuddata
    FLYWAY_ENABLED: true
    ACCOUNT_NAME: $(BLOB_ACCOUNT_NAME)
    ACCOUNT_KEY: $(BLOB_ACCESS_KEY)
    ENV_NAME: preview
    CONTAINER_NAME: jud-ref-data
    JRD_MQ_TRUST_ALL_CERTS: false
    JRD_DATA_PER_MESSAGE: 500
  keyVaults:
    rd:
      secrets:
        - CONTAINER-NAME
        - BLOB-URL-SUFFIX
        - ApplicationInsightsInstrumentationKey
        - judicial-topic-primary-connection-string
  secrets:
    BLOB_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    BLOB_ACCESS_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    BLOB_SERVICE_ENDPOINT:
      secretRef: storage-secret-{{ .Release.Name }}
      key: primaryBlobServiceEndPoint
    SB_TOPIC_CONN_STRING:
      secretRef: servicebus-secret-topic-${.Release.Name }-servicebus-jrd-aks-topic
      key: connectionString
global:
  jobKind: CronJob

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: dbjuddata
  postgresqlPassword: dbjuddata
  postgresqlDatabase: dbjuddata
  persistence:
    enabled: false

servicebus:
  resourceGroup: rd
  teamName: "RD"
  location: uksouth
  serviceplan: basic
  setup:
    topics:
      - name: jrd-aks-topic
  enabled: true

blobstorage:
  resourceGroup: rd
  teamName: "RD"
  location: uksouth
  setup:
    containers:
    - jud-ref-data
    - jud-ref-data-archive
  enabled: true
