job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: dbjuddata
    POSTGRES_USERNAME: dbjuddata
    POSTGRES_PASSWORD: dbjuddata
    FLYWAY_ENABLED: true
    ENV_NAME: preview
    CONTAINER_NAME: jud-ref-data
    JRD_MQ_TRUST_ALL_CERTS: false
    JRD_DATA_PER_MESSAGE: 500
    MAIL_FROM: no-reply@mail-rd-nonprod.platform.hmcts.net
  keyVaults:
    rd:
      secrets:
        - judicial-api-POSTGRES-PASS
        - ApplicationInsightsInstrumentationKey
        - name: ACCOUNT-NAME
          alias: ACCOUNT_NAME
        - name: ACCOUNT-KEY
          alias: ACCOUNT_KEY
        - name: CONTAINER-NAME
          alias: CONTAINER_NAME
        - name: judicial-topic-primary-connection-string
          alias: JUDICIAL_TOPIC_PRIMARY_CONNECTION_STRING
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: OAUTH2-CLIENT-SECRET
          alias: OAUTH2_CLIENT_SECRET
        - name: OAUTH2-AUTH
          alias: OAUTH2_AUTH
        - name: OAUTH2-CLIENT-AUTH
          alias: OAUTH2_CLIENT_AUTH
        - name: rd-sendgrid-api-key
          alias: RD_SENDGRID_API_KEY
  secrets:
    SB_TOPIC_CONN_STRING:
      secretRef: servicebus-secret-topic-{{ .Release.Name }}-servicebus-jrd-aks-topic
      key: connectionString
    BLOB_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    BLOB_ACCESS_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    BLOB_SERVICE_ENDPOINT:
      secretRef: storage-secret-{{ .Release.Name }}
      key: primaryBlobServiceEndPoint
global:
  jobKind: CronJob

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  postgresqlUsername: dbjuddata
  postgresqlPassword: dbjuddata
  postgresqlDatabase: dbjuddata
  persistence:
    enabled: false

servicebus:
  resourceGroup: rd-aks-pr-test
  teamName: "RD"
  location: ukwest
  serviceplan: standard
  setup:
    topics:
      - name: jrd-aks-topic
        subscriptionNeeded: yes
  enabled: true

blobstorage:
  resourceGroup: rd-aks-pr-test
  teamName: "RD"
  location: ukwest
  setup:
    containers:
      - jud-ref-data
      - jud-ref-data-archive
  enabled: true