job:
  applicationPort: 8094
  ingressHost: rd-judicial-data-load-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rd
  environment:
    POSTGRES_HOST: rd-judicial-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: dbjuddata@rd-judicial-api-postgres-db-{{ .Values.global.environment }}
    POSTGRES_PORT: 5432
    LOGBACK_REQUIRE_ALERT_LEVEL: 'false'
    LOGBACK_REQUIRE_ERROR_CODE: 'false'
    FLYWAY_ENABLED: false
    ENV_NAME: "{{ .Values.global.environment }}"
    CONTAINER_NAME: jud-ref-data
    JRD_MQ_TOPIC_NAME: rd-judicial-topic-{{ .Values.global.environment }}
    JRD_MQ_TRUST_ALL_CERTS: false
    JRD_DATA_PER_MESSAGE: 500
    IDAM_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    OAUTH2_REDIRECT_URI: https://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2redirect
  postgresql:
    enabled: false
  image: 'hmctspublic.azurecr.io/rd/judicial-data-load:latest'
  kind: CronJob
  schedule: "*/10 * * * *"
  global:
    jobKind: CronJob
  keyVaults:
    "rd":
      resourceGroup: rd
      secrets:
        - name: judicial-api-POSTGRES-PASS
          alias: spring.datasource.password
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: ACCOUNT-NAME
          alias: azure.storage.account-name
        - name: ACCOUNT-KEY
          alias: azure.storage.account-key
        - name: CONTAINER-NAME
          alias: azure.storage.container-name
        - name: BLOB-URL-SUFFIX
          alias: azure.storage.blob-url-suffix
        - name: judicial-topic-primary-connection-string
          alias: JRD_ASB_CONNECTION_KEY_STR
        - name: LD-SDK-KEY
          alias: RD_LD_SDK_KEY
        - name: OAUTH2-CLIENT-SECRET
          alias: idam.api-redirect-uri
        - name: OAUTH2-AUTH
          alias: idam.api.authorization
        - name: OAUTH2-CLIENT-AUTH
          alias: idam.api.client-authorization
        - name: SEARCH-QUERY-FROM
          alias: elastic.search.query
postgresql:
  enabled: false

servicebus:
  enabled: false


