spring:
  mail:
    to: test@hmcts.net
    subject: ${component.name:data-ingestion} - Exception in processing -
    host: mta.reform.hmcts.net
    port: 25
    enabled: ${mail.enabled:false}
  flyway:
    locations: classpath:db/testmigration
    enabled: true
  batch:
    initialize-schema: always
    # set batch false in integration test and run batch manually with batch runner to set dynamic test property values
    # eg. dynamic properties ${parent.file.name}
    job:
      enabled: false

start-route: direct:JRD
archival-route: direct:JrdArchival
archival-path: ${archival.path}
archival-file-names: ${archival.file.names}
archival-cred: credentials=#credsreg&operation=updateBlockBlob
archival-date-format: dd-MM-yyyy
active-blob-path: azure-blob://${azure.storage.account-name}/jud-ref-data
file-read-time-out: 2000
scheduler-audit-select: SELECT count(*) FROM dataload_schedular_audit WHERE DATE(scheduler_start_time) = current_date
scheduler-audit-prev-day: SELECT file_name, scheduler_start_time, status FROM dataload_schedular_audit WHERE DATE(scheduler_start_time) = current_date - INTEGER '1'
invalid-exception-sql: INSERT INTO dataload_exception_records(table_name,scheduler_start_time,scheduler_name,error_description,updated_timestamp) VALUES(?, ?, ?, ?, ?)
invalid-jsr-sql: INSERT INTO dataload_exception_records(table_name,scheduler_start_time,scheduler_name,key,field_in_error,error_description,updated_timestamp,row_id) VALUES(?, ?, ?, ?, ?, ?, ?, ?)
scheduler-insert-sql: INSERT INTO dataload_schedular_audit (scheduler_name,file_name, scheduler_start_time,scheduler_end_time,status) VALUES(?,?,?,?,?)
jsr-threshold-limit: 10
leaf-route-task: leafRouteTask
parent-route-task: parentRouteOrchestrationTask
batchjob-name: JudicialDataLoad
audit-enable: true

routes-to-execute-orchestration: judicial-user-profile-orchestration, judicial-office-appointment, judicial-office-authorisation
route:
  judicial-user-profile-orchestration:
    id: judicial-user-profile-orchestration
    file-name: ${parent.file.name:''}
    table-name: judicial_user_profile
    insert-sql:
      sql:INSERT INTO judicial_user_profile (per_id,personal_code,known_as,surname,full_name,post_nominals,work_pattern,ejudiciary_email,joining_date,last_working_date,
      active_flag,extracted_date,created_date,last_loaded_date,object_id,is_judge,is_panel_member,is_magistrate,mrd_created_time,mrd_updated_time,mrd_deleted_time)
      VALUES(:#per_id,:#personal_code,:#known_as,:#surname,:#full_name,:#post_nominals,
      :#work_pattern, :#ejudiciary_email,TO_DATE(NULLIF(:#joining_date,''), 'yyyy-MM-dd'),TO_DATE(NULLIF(:#last_working_date,''), 'yyyy-MM-dd'),:#active_flag,
      :#extracted_date, NOW() AT TIME ZONE 'utc', NOW() AT TIME ZONE 'utc', :#object_id, :#is_judge, :#is_panel_member, :#is_magistrate,
      :#mrd_created_time, :#mrd_updated_time, :#mrd_deleted_time) ON CONFLICT (per_id) DO UPDATE SET personal_code = :#personal_code,
      known_as = :#known_as, surname = :#surname, full_name = :#full_name, post_nominals =:#post_nominals,
      work_pattern = :#work_pattern, ejudiciary_email = :#ejudiciary_email, joining_date = TO_DATE(NULLIF(:#joining_date,''), 'yyyy-MM-dd'),
      last_working_date = TO_DATE(NULLIF(:#last_working_date,''), 'yyyy-MM-dd'), active_flag = :#active_flag,
      :#extracted_date, last_loaded_date = NOW() AT TIME ZONE 'utc' ,object_id = :#object_id,
      is_judge = :#is_judge, is_panel_member = :#is_panel_member, is_magistrate = :#is_magistrate,
      mrd_created_time = :#mrd_created_time, mrd_updated_time = :#mrd_updated_time, mrd_deleted_time = :#mrd_deleted_time?batch=true&dataSource=dataSource
    blob-path: ${parent.file.path}
    processor-class: JudicialUserProfileProcessor
    mapper-class: JudicialUserProfileRowMapper
    csv-binder-object: JudicialUserProfile

  judicial-office-appointment:
    id: judicial-office-appointment
    file-name: ${child.file.name}
    table-name: judicial-office-appointment
    parent-failure-enabled: true
    parent-name: Personal
    truncate-sql:
      sql:TRUNCATE judicial_office_appointment RESTART IDENTITY?dataSource=dataSource&batch=true
    insert-sql:
      sql:INSERT INTO judicial_office_appointment (judicial_office_appointment_id,per_id,base_location_id,region_id,is_prinicple_appointment,start_date,end_date,active_flag,extracted_date,created_date,last_loaded_date,personal_code,object_id,
      appointment,appointment_type)
      VALUES(:#judicial_office_appointment_id, :#per_id, :#base_location_id, :#region_id, :#is_prinicple_appointment,
      TO_DATE(NULLIF(:#start_date,''), 'yyyy-MM-dd'), TO_DATE(NULLIF(:#end_date,''), 'yyyy-MM-dd'), :#active_flag, :#extracted_date,NOW() AT TIME ZONE 'utc',NOW() AT TIME ZONE 'utc', :#personal_code, :#object_id,
      :#appointment, :#appointment_type)?dataSource=dataSource&batch=true
    blob-path: ${child.file.path}
    processor-class: JudicialOfficeAppointmentProcessor
    mapper-class: JudicialOfficeAppointmentRowMapper
    csv-binder-object: JudicialOfficeAppointment

  judicial-office-authorisation:
    id: judicial-office-authorisation
    file-name: ${child1.file.name}
    table-name: judicial_office_authorisation
    parent-failure-enabled: true
    parent-name: Personal
    truncate-sql:
      sql:TRUNCATE TABLE judicial_office_authorisation RESTART IDENTITY?dataSource=dataSource
    insert-sql:
      sql:INSERT INTO judicial_office_authorisation (judicial_office_auth_id,per_id,jurisdiction,ticket_id,start_date,end_date,created_date,last_updated,lower_level,personal_code,object_id,mrd_created_time,mrd_updated_time,mrd_deleted_time)
      VALUES(:#judicial_office_auth_id,:#per_id,:#jurisdiction,:#ticket_id,:#start_date,:#end_date,NOW() AT TIME ZONE 'utc',NOW() AT TIME ZONE 'utc',:#lower_level,:#personal_code, :#object_id ,:#mrd_created_time,:#mrd_updated_time,:#mrd_deleted_time)?batch=true&dataSource=dataSource
    blob-path: ${child1.file.path}
    processor-class: JudicialOfficeAuthorisationProcessor
    mapper-class: JudicialOfficeAuthorisationRowMapper
    csv-binder-object: JudicialOfficeAuthorisation

parent-select-jrd-sql: SELECT * FROM judicial_user_profile ORDER BY per_id

child-select-child1-sql: SELECT * FROM judicial_office_appointment ORDER BY per_id

child-select-child2-sql: SELECT * FROM judicial_office_authorisation ORDER BY per_id

exception-select-query: SELECT * FROM  dataload_exception_records

select-dataload-schedular-audit: SELECT * FROM dataload_schedular_audit

select-dataload-scheduler-audit-failure: SELECT * FROM dataload_schedular_audit WHERE status='Failure'

select-dataload-scheduler-audit-partial-success: SELECT *  FROM dataload_schedular_audit WHERE status='PartialSuccess'

select-dataload-scheduler-audit-success: SELECT *  FROM dataload_schedular_audit WHERE status='Success'

start-leaf-route: direct:leaf

truncate-audit: TRUNCATE dataload_schedular_audit

truncate-exception: TRUNCATE dataload_exception_records

truncate-job: TRUNCATE dataload_schedular_job

fetch-personal-per-id: SELECT per_id FROM judicial_user_profile

jdbc-batch-size: 10

logging-component-name: RD_Judicial_Ref_Data
component:
  name: Judicial Reference Data
mail:
  enabled: true

idempotent-flag-ingestion: true

insert-job-sql: INSERT INTO dataload_schedular_job(job_start_time, publishing_status) VALUES(?, ?)
update-job-sql: UPDATE dataload_schedular_job set job_end_time = NOW() AT TIME ZONE 'utc', publishing_status = ? WHERE id =?
select-job-status-sql: SELECT id, publishing_status FROM dataload_schedular_job WHERE DATE(job_start_time) = current_date
previous-day-job-status: SELECT id, publishing_status FROM dataload_schedular_job WHERE DATE(job_start_time) = current_date - INTEGER '1'
get-sidam-ids: SELECT distinct sidam_id FROM judicial_user_profile WHERE sidam_id is not NULL
scheduler-audit-failure: SELECT count(*) FROM dataload_schedular_audit WHERE DATE(scheduler_start_time) = current_date AND status = 'Failure'
scheduler-end-time: SELECT MAX(scheduler_end_time) FROM dataload_schedular_audit WHERE scheduler_end_time < ( SELECT MAX(scheduler_end_time) FROM dataload_schedular_audit WHERE file_name = 'Personal-Test' AND status IN ('PartialSuccess', 'Success')) AND file_name = 'Personal-Test' AND status IN ('PartialSuccess', 'Success')
update-sidam-ids: UPDATE judicial_user_profile set sidam_id = ? WHERE object_id = ? AND sidam_id is NULL
failed-records-exception: SELECT * FROM dataload_exception_records WHERE error_description = ? AND table_name = ?;

jrd:
  publisher:
    azure:
      service:
        bus:
          connection-string: ${JRD_ASB_CONNECTION_KEY_STR:}
          topic: jrd-aks-topic
          trustAllCerts: ${JRD_MQ_TRUST_ALL_CERTS:false}
    jrd-message-batch-size: ${JRD_DATA_PER_MESSAGE:5}

launchdarkly:
  sdk:
    key: ${LD_SDK_KEY:}
    environment: ${ENV_NAME:local}
    user: rd

elastic:
  search:
    query: ${JRD_SIDAM_SEARCH_QUERY:(roles:judiciary) AND lastModified:>now-%sh}
    recordsPerPage: 500

idam:
  api:
    url: ${IDAM_URL:https://idam-api.aat.platform.hmcts.net}
    client-id: ${OAUTH2_CLIENT_ID:rd-professional-api}
    redirect-uri: ${OAUTH2_REDIRECT_URI:https://rd-professional-api-aat.service.core-compute-aat.internal/oauth2redirect}
    authorization: ${OAUTH2_AUTH:}
    client-authorization: ${OAUTH2_CLIENT_AUTH:}


sendgrid:
  key: ${SENDGRID_API_KEY:}
  mail:
    from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}

email:
  mailTypes:
    asb:
      enabled: true
      from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}
      to:
        - DLRefDataSupport@hmcts.net
      subject: "%s :: Publishing of JRD messages to ASB failed"
      body: "Publishing of JRD messages to ASB failed for Job Id %s"
    report:
      enabled: false
      from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}
      to:
        - DLRefDataSupport@hmcts.net
      subject: "%s :: JRD - Execution Failed"
      body: "Execution Failed for files - %s"
    userprofile:
      enabled: true
      from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}
      to:
        - pradipta.dey@hmcts.net
        - candyliyen.kuek@hmcts.net
      subject: "Official Sensitive: JRD - Incorrect JO Profile Configurations - %s"
      body: "Following JO profiles were deleted : \n %s"
    lowerLevelAuth:
      enabled: true
      from: ${MAIL_FROM:no-reply@mail-rd-nonprod.platform.hmcts.net}
      to:
        - pradipta.dey@hmcts.net
        - candyliyen.kuek@hmcts.net
      subject: "Official Sensitive: JRD - New Lower Level in Authorisations - %s"
      template: lower-level-auth.ftl