spring:
  datasource:
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: ${DB_URL:jdbc:tc:postgresql:11.1:///dbjuddata-test}
    username: ${DB_USERNAME:dbjuddata-test}
    password: ${DB_PASSWORD:dbjuddata-test}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false